[build]
  publish = "."
  functions = "netlify/functions"

# Step 5 — cache + background refresh
# The "latest" function is our on-demand endpoint for fetching tenders.
[[redirects]]
  from = "/api/latest"
  to = "/.netlify/functions/latest"
  status = 200
  force = true

# Background function runs every morning at 09:05 UTC
[functions.update-tenders-background]
  schedule = "5 9 * * *"
