[build]
  functions = "netlify/functions"
  publish = "public"  # or "." if you have no front-end

[functions]
  node_bundler = "esbuild"

  [functions.update-tenders-background]
  schedule = "0 8,9 * * *"
