[functions."update-tenders-background"]
  schedule = "0 */3 * * *" # every 3 hours UTC

[[functions."update-tenders-background".schedule]]
  cron = "0 9 * * *" # 9 AM UK winter (UTC)
[[functions."update-tenders-background".schedule]]
  cron = "0 8 * * *" # 9 AM UK summer (UTC+1)
