[build]
  publish = "."
  functions = "netlify/functions"

# Optional: schedule a background refresh once each morning (09:05 UK time ~ 09:05 UTC winter)
[functions.update-tenders-background]
  schedule = "5 9 * * *"
