[build]
  publish = "."

[functions]
  node_bundler = "esbuild"
  node_version = "18"

# This is the key line — enables the modern functions runtime
[functions."*"]
  included_files = ["!node_modules/**"]

[[plugins]]
  package = "@netlify/plugin-functions-core"
