[functions]
  directory = "netlify/functions"

# Scheduled run: 9 AM UK time (08:00 UTC during winter, 07:00 UTC during summer)
[[functions."update-tenders-background".schedule]]
  cron = "0 9 * * *"

# Build settings
[build]
  publish = "public"
  command = "npm install && npm run build"

# Environment for Node fetch + blobs
[functions.environment]
  NODE_VERSION = "18"
