[build]
  command = ""
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch", "@netlify/blobs"]

# Scheduled background run at 9 AM UK time (UTC in winter)
[[functions."update-tenders-background".schedule]]
  cron = "0 9 * * *"
