[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions.update-tenders-background]
  schedule = "0 9 * * *" # Runs daily at 9 AM UK time

# Allow calling update-tenders-background manually via browser
[[redirects]]
  from = "/update-tenders-background"
  to = "/.netlify/functions/update-tenders-background"
  status = 200

[[redirects]]
  from = "/latest"
  to = "/.netlify/functions/latest"
  status = 200
