[build]
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

# Run the fetcher every 5 minutes
[[scheduled.functions]]
  path = "fetch-contracts"
  schedule = "*/5 * * * *"
