[build]
  functions = "netlify/functions"
  publish   = "."

[functions."update-tenders-background"]
  schedule = "0 */3 * * *" # every 3 hours UTC
[[functions."update-tenders-background".schedule]]
  cron = "0 9 * * *" # 9 AM UK time (winter)
[[functions."update-tenders-background".schedule]]
  cron = "0 8 * * *" # 9 AM UK time (summer - UTC+1)
