[build]
  functions = "netlify/functions"
  publish   = "."

# Winter schedule (UK time = GMT)
[[scheduled.functions]]
  path = "update-tenders-background"
  schedule = "0 9 * * *"

# Summer schedule (UK time = BST)
[[scheduled.functions]]
  path = "update-tenders-background"
  schedule = "0 8 * * *"
